#region FirstRegion
all:
	@echo "Building project..."
#endregion

#region SecondRegion
clean:
	rm -rf build/
	#      region   InnerRegion  
	rm -rf logs/
	#endregion   ends  InnerRegion 
	rm -rf temp/
	#region  
	rm -rf cache/
	#   endregion  
#   endregion
